openapi: 3.0.0
info:
  description: All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
  title: Sage HR Documents Onboarding API
  version: '1.0'
  x-konfig-ignore:
    potential-incorrect-type: true
  x-konfig-uses-multipart-form-data: true
servers:
- url: https://subdomain.sage.hr/api
tags:
- name: Onboarding
paths:
  /onboarding/categories:
    summary: Onboarding task categories
    get:
      operationId: Onboarding_listTaskCategories
      responses:
        '200':
          content:
            application/json:
              examples:
                response:
                  value:
                    data:
                    - title: General
                      id: 1
                    - title: Platform
                      id: 2
              schema:
                $ref: '#/components/schemas/OnboardingListTaskCategoriesResponse'
          description: Successful Response
      summary: List onboarding task categories
      tags:
      - Onboarding
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--onboarding-categories
      x-accepts: application/json
  /onboarding/tasks:
    summary: Onboarding task
    post:
      operationId: Onboarding_createNewTask
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OnboardingCreateNewTaskRequest'
        required: true
      responses:
        '201':
          content:
            application/json:
              examples:
                response:
                  value:
                    data:
                      id: 1
              schema:
                $ref: '#/components/schemas/OnboardingCreateNewTaskResponse'
          description: Successful Response
      summary: Create new onboarding task
      tags:
      - Onboarding
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--onboarding-tasks
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
components:
  schemas:
    OnboardingCreateNewTaskResponse_data:
      properties:
        id:
          example: 1
          type: number
          x-konfig-original-example: 1
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-OnboardingCreateNewTaskResponse-properties-data-properties-id
      type: object
    OnboardingCreateNewTaskResponse:
      example:
        data:
          id: 1
      properties:
        data:
          $ref: '#/components/schemas/OnboardingCreateNewTaskResponse_data'
      type: object
      x-konfig-original-example:
        data:
          id: 1
      x-konfig-generated-schema: konfig-generated-schema-components-schemas-OnboardingCreateNewTaskResponse
      x-konfig-is-used-in-successful-response: true
    OnboardingListTaskCategoriesResponse:
      example:
        data:
        - title: General
          id: 1
        - title: Platform
          id: 2
      properties:
        data:
          items:
            $ref: '#/components/schemas/OnboardingListTaskCategoriesResponse_data_inner'
          type: array
      type: object
      x-konfig-original-example:
        data:
        - title: General
          id: 1
        - title: Platform
          id: 2
      x-konfig-generated-schema: konfig-generated-schema-components-schemas-OnboardingListTaskCategoriesResponse
      x-konfig-is-used-in-successful-response: true
    OnboardingCreateNewTaskRequest:
      properties:
        title:
          type: string
        description:
          type: string
        boarding_task_template_category_id:
          type: number
        due_in:
          description: Due date in days after employee start date
          example: 30
          type: number
          x-konfig-original-example: 30
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-OnboardingCreateNewTaskRequest-properties-due_in
        default_assignee_type:
          description: 'Default: self; leader - direct manager; employee - specific employee via assignee_id'
          enum:
          - self
          - leader
          - employee
          type: string
        assignee_id:
          description: Specific assignee if default_assignee_type is 'employee'
          type: number
        require_attachment:
          description: '''true'' to enabled required attachment'
          type: string
        add_after:
          description: Task start date in days after employee start date
          type: number
      required:
      - boarding_task_template_category_id
      - due_in
      - title
      type: object
    OnboardingListTaskCategoriesResponse_data_inner:
      properties:
        title:
          example: General
          type: string
          x-konfig-original-example: General
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-OnboardingListTaskCategoriesResponse-properties-data-items-properties-title
        id:
          example: 1
          type: number
          x-konfig-original-example: 1
          x-konfig-generated-schema: konfig-generated-schema-components-schemas-OnboardingListTaskCategoriesResponse-properties-data-items-properties-id
      type: object
  securitySchemes:
    api_key:
      description: All request are required to pass a `X-Auth-Token` header.
      in: header
      name: X-Auth-Token
      type: apiKey
      x-konfig-globally-required-security: false
